# This is a starting workflow for building with GitHub Actions
name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out code
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      # Set up the build environment
      - name: Copy our kickstart file over so it gets picked up
        run: mkdir faDockerComposeFilePath/ && cp -r .github/kickstart faDockerComposeFilePath/ && cp .github/kickstart/kickstart.json faDockerComposeFilePath/kickstart/k2.json
      - name: Start FusionAuth
        uses: fusionauth/fusionauth-github-action@v1
        with:
          FUSIONAUTH_APP_KICKSTART_FILENAME: k2.json
          FUSIONAUTH_VERSION: 1.51.1
          FUSIONAUTH_APP_KICKSTART_DIRECTORY_PATH: .github/kickstart

      - name: Debugging network info
        run: docker network ls
      # Compile
      - name: Test that we can compile
        run: cd pkg/fusionauth && go build
      # Compile
      - name: Run tests
        run: cd pkg/fusionauth && go test
      # Done!
