# Run locally with act:
#
# act pull_request [--input command=[command]] \
#  --platform fusionauth-builder=[ecr-repo-name]/fusionauth-builder:latest] \
#  --workflows ./.github/workflows/release.yaml \
#  --env-file <(aws configure export-credentials --profile [aws-profile] --format env)

name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      command:
        type: choice
        options:
          - test     # build only
          - release  # build & release to svn
        default: build

permissions:
  contents: read

jobs:
  test:
    if: |
      github.event_name == 'pull_request' ||
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' && inputs.command == 'test'
    runs-on: fusionauth-standard
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Copy our kickstart file over so it gets picked up
        run: |
          mkdir faDockerComposeFilePath
          cp -r .github/kickstart faDockerComposeFilePath
          cp .github/kickstart/kickstart.json faDockerComposeFilePath/kickstart/k2.json
          cp .github/kickstart/kickstart.json .github/kickstart/k2.json

      - name: Start FusionAuth
        uses: fusionauth/fusionauth-github-action@v1
        with:
          FUSIONAUTH_APP_KICKSTART_FILENAME: k2.json
          FUSIONAUTH_APP_KICKSTART_DIRECTORY_PATH: .github/kickstart

      - name: Sleep until FusionAuth starts
        run: sleep 30
      - name: Test that we can compile
        shell: bash -l {0}
        run: sb compile
      - name: Run tests
        shell: bash -l {0}
        run: sb test

  deploy:
    if: |
      github.event_name == 'workflow_dispatch' && inputs.command == 'release'
    runs-on: fusionauth-builder
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: release to svn
        if: inputs.command == 'release'
        shell: bash -l {0}
        run: sb release
